# Generated by Django 4.2.1 on 2023-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_lugar', models.CharField(max_length=8)),
                ('uf_lugar', models.CharField(max_length=2)),
                ('distrito_lugar', models.CharField(max_length=50)),
                ('logradouro_lugar', models.TextField(blank=True)),
            ],
        ),
    ]
