# Generated by Django 4.2.1 on 2023-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0003_alter_lugar_distrito_lugar_alter_lugar_uf_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='distrito_lugar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='uf_lugar',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
